### ISSUE TITLE
Wrong object passed to onNext for some functions

### ISSUE THREAD

**Issue by midnite8177** [Reactive-Extensions/rxjs-jquery#13]
Looking at the source of rx.jquery.js there is intention of passing the jQuery object through the observable when it triggers, but there is some mismanagement of 'this' causing it to be the DOM element passed through and not the intended and expected jQuery object.

handeAnimation (note the misspelling) should be passing jQueryProto to the subject.onNext call, and not 'this'

proto.animateAsObservable should capture 'this' to a local and that local passed to the subject.onNext call inside the complete callback.

proto.fadeToAsObservable should do the same thing as above

**Comment by mattpodwysocki** [comment]
Fixed as per 1.1.5

**Comment by midnite8177** [comment]
Shouldn't proto be passed to onNext in of 'animateAsObservable' also?
