### ISSUE TITLE
leaking handlers?

### ISSUE THREAD

**Issue by acthp** [Reactive-Extensions/rxjs-jquery#19]
Do these methods leak handlers when a DOM element is destroyed? I see that they return disposables, so the observer can unsubscribe. But I don't see a way for the observable to complete the stream when the DOM element is destroyed.

**Comment by mattpodwysocki** [comment]
@acthp Is there a way I can hook into the destroy for the particular object?  If not, you can always add it to a CompositeDisposable and then when the page lifecycle is what it is, then it goes away when removed.  Else, you could have takeUntil which destroys the event handler.
