### ISSUE TITLE
Bring back toObservable

### ISSUE THREAD

**Issue by cburgdorf** [Reactive-Extensions/rxjs-jquery#4]
Is it intentional that toObservable has gone? Can we just add it as an alias for bindAsObservable(). This looks really verbose to my eyes.

**Comment by mattpodwysocki** [comment]
I'd prefer not to bring back toObservable unless it were to use on instead.  I'd rather be explicit though about which action it is as in bind, live, delegate or on.

**Comment by cburgdorf** [comment]
I understand your point. But I'm a bit concerned with all those examples used in slides, blog posts that show "toObservable". For my codebase I just created an alias because I don't want to search & destroy through the entire code base. But I'm a bit worried about people trying old example that now won't work anymore.
