### ISSUE TITLE
bindAsObservable and others do not support extraParameters

### ISSUE THREAD

**Issue by bman654** [Reactive-Extensions/rxjs-jquery#5]
```
$(...).bind('eventType', function (ev, a, b) { })
      .trigger('eventType', [ 'val1', 'val2' ]);
```

will pass 'val1' and 'val2' as the 2nd and 3rd argument to the event handler.   `bindAsObservable()` (and other "AsObservable" versions) only captures the event object.  Could these methods be changed to add the additional arguments as a property on the event object?  Something like this in the handler:  `eventObject.additionalArguments = arguments.slice(1);`

**Comment by mattpodwysocki** [comment]
Yes, that could work, I'll get that in there.

**Comment by mattpodwysocki** [comment]
Done
