### ISSUE TITLE
value.data.length returns undefined.

### ISSUE THREAD

**Issue by tcsatheesh** [Reactive-Extensions/rxjs-jquery#7]
Tried this on IE 10 and the latest Chrome but value.data.length is returning as undefined. Value.data does contain two items. index 0 is the search text and index 1 is the results.

**Comment by mattpodwysocki** [comment]
Can you give me a full reproduction?  Which method is causing this?

**Comment by tcsatheesh** [comment]
Life's little challenges. :( I cannot find a way to attach a zip file of a visual studio project here.See screenshot
![screenshot](https://f.cloud.github.com/assets/5278951/1017491/ebb40fd0-0c11-11e3-9c31-c1ac82ff4aa3.PNG)

**Comment by mattpodwysocki** [comment]
Yep, I see it and I fixed that issue in https://github.com/Reactive-Extensions/rxjs-jquery/commit/de5b181a7ad7b70d3b484c0c6177d4135ca1e0ba
