### ISSUE TITLE
Deferred toObservable unavailable

### ISSUE THREAD

**Issue by acthp** [Reactive-Extensions/rxjs-jquery#8]
Is there a usage example for Deferred.toObservable?  rxjs-jquery attempts to modify the prototype for $.Deferred, but $.Deferred returns an object literal. Deferred.prototype is not involved, so the function is unavailable on deferred objects. It can still be called like

$.Deferred.prototype.toObservable.call(deferred)

but I doubt that this is the expected usage.

Perhaps the prototype extension works with particular versions of jquery. Is there a list of supported jquery versions?

**Comment by mattpodwysocki** [comment]
That's a bug, just fixed as of: https://github.com/Reactive-Extensions/rxjs-jquery/commit/6df0373d92be45e9b55810877ec9c1fa80b81e57

The expected usage is as follows:

``` js
var deferred = $.Deferred();
var observable = $.Deferred.toObservable(deferred);

observable.subscribe(function (x) {
    console.log(x);
});

deferred.resolve(42);

```
