### ISSUE TITLE
bower install for 1.1.1 fails

### ISSUE THREAD

**Issue by AdamNowotny** [Reactive-Extensions/rxjs-jquery#9]
Installing the newest version through bower fails for 1.1.1 with "Package rx not found". It works fine for 1.0.1.
I think the dependency package name should be rxjs, but `bower info rxjs-jquery` shows:

```
dependencies: {
  rx: '*'
}
```

**Comment by mattpodwysocki** [comment]
I'll investigate, but if you look at the bower.json in RxJS, it's Rx: https://github.com/Reactive-Extensions/RxJS/blob/master/bower.json

**Comment by AdamNowotny** [comment]
I was referencing "rxjs" as another dependency, so I guess that's changed now. When updated to "Rx" it's all fine.
